clear;
restoredefaultpath;
p = path;
basepath = 'C:\Users\Frys\Documents\Barrows Work\ALL TEXT FILES2\';
listOfFiles = { '10.04.13' ...
                '10.02.13' ...
                '9.30.13' ...
                '9.28.13' ...
                '7.28.13' ...
                '7.27.13' ...
                '7.25.13' ...
                '7.21.13' ...
                '7.19.13' ...
                '7.17.13' ...
                '7.16.13' ...
                }; 
task = 'Flat';
stepNum = 3;
% Allows for multiple recordings to be processed by kinem_cat at once
for i = 1:length(listOfFiles)
    disp([listOfFiles{i} ' is being processed'])
    path([basepath listOfFiles{i} '\' task],p);
    kinem_cat(listOfFiles{i},task,stepNum);
    path(p)
end
%Unanalyzed Files: 6.25.13 7.23.13
 

